import { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';

interface RootLayoutProps {
    children: React.ReactNode;
}

const geistSans = Geist({
    subsets: ['latin'],
    variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
    subsets: ['latin'],
    variable: '--font-geist-mono',
});

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
};

function RootLayout({ children }: Readonly<RootLayoutProps>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}

export default RootLayout;
